name: forge2d_game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  characters: ^1.3.0
  equatable: ^2.0.5
  flame: ^1.18.0
  flame_forge2d: ^0.18.1
  flame_kenney_xml: ^0.1.0
  flutter:
    sdk: flutter
  forge2d: ^0.13.0
  ordered_set: ^5.0.3
  petitparser: ^6.0.2
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
